name: Bug Report
description: Signaler un bug rencontré dans le projet
title: "[BUG] Décrivez brièvement le problème"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Merci de signaler un bug ! Veuillez remplir les sections ci-dessous pour nous aider à le résoudre plus rapidement.

  - type: input
    id: summary
    attributes:
      label: Résumé du bug
      description: Résumez le bug en une phrase.
      placeholder: "Exemple : L'application plante lors du clic sur 'Enregistrer'."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Étapes pour reproduire le bug
      description: Décrivez les étapes nécessaires pour reproduire le bug.
      placeholder: |
        1. Allez à '...'
        2. Cliquez sur '...'
        3. Observez le problème.
