name: Feature request
description: Suggérer une nouvelle idée ou fonctionnalité
title: "[FEATURE] Décrivez votre idée"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Merci de partager vos idées pour améliorer ce projet !

  - type: input
    id: feature_description
    attributes:
      label: Description de la fonctionnalité
      description: Expliquez clairement ce que vous proposez.
      placeholder: Décrivez votre idée ou fonctionnalité souhaitée.
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Cas d'utilisation
      description: Expliquez pourquoi cette fonctionnalité serait utile.
      placeholder: Donnez un exemple concret ou un contexte.

  - type: textarea
    id: possible_approach
    attributes:
      label: Approche possible
      description: Partagez vos idées sur la façon de mettre en œuvre cette fonctionnalité.
      placeholder: Décrivez les étapes ou l'implémentation technique si vous en avez une idée.

  - type: textarea
    id: additional_info
    attributes:
      label: Informations supplémentaires
      description: Ajoutez tout ce qui pourrait être pertinent (liens, schémas, etc.).
      placeholder: Autres détails ici.
