name: Issue Response

on:
  issues:
    types: [opened]

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Send a response
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Merci pour votre issue, notre équipe va se pencher dessus !'
          })